-- Oracle Schema Migration
-- V1__Create_base_tables.sql

-- Account Table
CREATE TABLE account (
    account_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR2(100) NOT NULL,
    balance NUMBER(19, 2) DEFAULT 0.00 NOT NULL,
    version NUMBER(10) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_account_user_name ON account(user_name);

COMMENT ON TABLE account IS 'Account table for transaction demos';

-- Order Table
CREATE TABLE orders (
    order_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER(19) NOT NULL,
    product_name VARCHAR2(200) NOT NULL,
    amount NUMBER(19, 2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_account FOREIGN KEY (account_id) REFERENCES account(account_id)
);

CREATE INDEX idx_orders_account_id ON orders(account_id);
CREATE INDEX idx_orders_status ON orders(status);

COMMENT ON TABLE orders IS 'Order table for transaction demos';

-- Inventory Table
CREATE TABLE inventory (
    inventory_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(200) NOT NULL UNIQUE,
    quantity NUMBER(10) DEFAULT 0 NOT NULL,
    version NUMBER(10) DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_inventory_product_name ON inventory(product_name);

COMMENT ON TABLE inventory IS 'Inventory table for transaction demos';

-- Transaction Log Table
CREATE TABLE transaction_log (
    log_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_type VARCHAR2(100) NOT NULL,
    operation VARCHAR2(200) NOT NULL,
    status VARCHAR2(20) NOT NULL,
    details CLOB,
    executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_txlog_type ON transaction_log(transaction_type);
CREATE INDEX idx_txlog_executed_at ON transaction_log(executed_at);

COMMENT ON TABLE transaction_log IS 'Transaction execution log';

-- Redo Log Simulation Table
CREATE TABLE redo_log_simulation (
    log_sequence_number NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR2(100) NOT NULL,
    operation_type VARCHAR2(20) NOT NULL,
    table_name VARCHAR2(100) NOT NULL,
    before_image CLOB,
    after_image CLOB,
    log_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_redo_tx_id ON redo_log_simulation(transaction_id);
CREATE INDEX idx_redo_log_time ON redo_log_simulation(log_time);

COMMENT ON TABLE redo_log_simulation IS 'Redo log simulation for demos';

-- Undo Log Simulation Table
CREATE TABLE undo_log_simulation (
    undo_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR2(100) NOT NULL,
    rollback_sql CLOB NOT NULL,
    rollback_data CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_undo_tx_id ON undo_log_simulation(transaction_id);

COMMENT ON TABLE undo_log_simulation IS 'Undo log simulation for demos';

-- MVCC Version Chain Table
CREATE TABLE mvcc_version_chain (
    version_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_id NUMBER(19) NOT NULL,
    transaction_id VARCHAR2(100) NOT NULL,
    data_snapshot CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE INDEX idx_mvcc_row_id ON mvcc_version_chain(row_id);
CREATE INDEX idx_mvcc_tx_id ON mvcc_version_chain(transaction_id);

COMMENT ON TABLE mvcc_version_chain IS 'MVCC version chain simulation';

-- Create trigger for account updated_at
CREATE OR REPLACE TRIGGER trg_account_updated_at
BEFORE UPDATE ON account
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Create trigger for inventory updated_at
CREATE OR REPLACE TRIGGER trg_inventory_updated_at
BEFORE UPDATE ON inventory
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/
